apiVersion: v1
kind: PersistentVolume
metadata:
  name: a960dc3b-9fd1-4dbb-80fd-c60f8718f3c7
  annotations:
        scheduler.alpha.kubernetes.io/affinity: >
            {
              "nodeAffinity": {
                "requiredDuringSchedulingIgnoredDuringExecution": {
                  "nodeSelectorTerms": [
                    {
                      "matchExpressions": [
                        {
                          "key": "kubernetes.io/hostname",
                          "operator": "In",
                          "values": ["192.168.165.212"]
                        }
                      ]
                    }
                  ]
                }
              }
            }
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /root/k8s-local-pv/a960dc3b-9fd1-4dbb-80fd-c60f8718f3c7
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 7b90e439-8d3f-4cfa-b658-470fc357bc23
  annotations:
        scheduler.alpha.kubernetes.io/affinity: >
            {
              "nodeAffinity": {
                "requiredDuringSchedulingIgnoredDuringExecution": {
                  "nodeSelectorTerms": [
                    {
                      "matchExpressions": [
                        {
                          "key": "kubernetes.io/hostname",
                          "operator": "In",
                          "values": ["192.168.165.213"]
                        }
                      ]
                    }
                  ]
                }
              }
            }
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  hostPath:
    path: /root/k8s-local-pv/7b90e439-8d3f-4cfa-b658-470fc357bc23
