apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  labels:
    name: graphite
  name: graphite
spec:
  type: NodePort
  ports:
  - name: carboncache
    port: 2003
  - name: pickle
    port: 2004
  - name: api
    port: 80
  selector:
    name: graphite
