apiVersion: v1
kind: ReplicationController
metadata:
  namespace: kube-system
  name: graphite
  labels:
    name: graphite
spec:
  replicas: 1
  selector:
    name: graphite
  template:
    metadata:
      labels:
        name: graphite
    spec:
      containers:
      - name: graphite
        image: hopsoft/graphite-statsd:latest
        ports:
        - name: graphite
          containerPort: 2003
        - name: pickle
          containerPort: 2004
        - name: api
          containerPort: 80
        livenessProbe:
          initialDelaySeconds: 100
          timeoutSeconds: 10
          httpGet:
            path: /
            port: 80
        livenessProbe:
          initialDelaySeconds: 100
          timeoutSeconds: 10
          tcpSocket:
            port: 2003
        volumeMounts:
        - name: configvolume
          mountPath: /opt/graphite/conf/storage-schemas.conf
          subPath: storage-schemas.conf
      volumes:
        - name: configvolume
          configMap:
            name: graphite-storage-schemas
